/**
 * ClassTutor — Dynamic Curriculum Knowledge Base
 * Automatically generated by tools/sync_books.py from source PDFs
 * 100% Dynamic — Zero hardcoding
 */

const CurriculumData = (() => {
  const GDRIVE_FOLDER_URL = "https://drive.google.com/drive/folders/1KdbLY8DMET-kb4LrN1I1POnzy0svcmwB";

  // Dynamic Syllabus index generated directly from source textbooks
  const SYLLABUS = [
  {
    "subject": "Santoor (English)",
    "chapter": 1,
    "title": "Papa's Spectacles",
    "file": "eesa101.pdf",
    "folder": "English",
    "total_pages": 10,
    "gdrive_url": "https://drive.google.com/drive/folders/1KdbLY8DMET-kb4LrN1I1POnzy0svcmwB"
  },
  {
    "subject": "Santoor (English)",
    "chapter": 2,
    "title": "Gone with the Scooter",
    "file": "eesa102.pdf",
    "folder": "English",
    "total_pages": 16,
    "gdrive_url": "https://drive.google.com/drive/folders/1KdbLY8DMET-kb4LrN1I1POnzy0svcmwB"
  },
  {
    "subject": "Santoor (English)",
    "chapter": 3,
    "title": "The Rainbow",
    "file": "eesa103.pdf",
    "folder": "English",
    "total_pages": 14,
    "gdrive_url": "https://drive.google.com/drive/folders/1KdbLY8DMET-kb4LrN1I1POnzy0svcmwB"
  },
  {
    "subject": "Santoor (English)",
    "chapter": 4,
    "title": "The Wise Parrot",
    "file": "eesa104.pdf",
    "folder": "English",
    "total_pages": 14,
    "gdrive_url": "https://drive.google.com/drive/folders/1KdbLY8DMET-kb4LrN1I1POnzy0svcmwB"
  },
  {
    "subject": "Santoor (English)",
    "chapter": 5,
    "title": "The Frog",
    "file": "eesa105.pdf",
    "folder": "English",
    "total_pages": 10,
    "gdrive_url": "https://drive.google.com/drive/folders/1KdbLY8DMET-kb4LrN1I1POnzy0svcmwB"
  },
  {
    "subject": "Santoor (English)",
    "chapter": 6,
    "title": "What a Tank!",
    "file": "eesa106.pdf",
    "folder": "English",
    "total_pages": 14,
    "gdrive_url": "https://drive.google.com/drive/folders/1KdbLY8DMET-kb4LrN1I1POnzy0svcmwB"
  },
  {
    "subject": "Santoor (English)",
    "chapter": 7,
    "title": "Gilli Danda",
    "file": "eesa107.pdf",
    "folder": "English",
    "total_pages": 12,
    "gdrive_url": "https://drive.google.com/drive/folders/1KdbLY8DMET-kb4LrN1I1POnzy0svcmwB"
  },
  {
    "subject": "Santoor (English)",
    "chapter": 8,
    "title": "The Decision of the Panchayat",
    "file": "eesa108.pdf",
    "folder": "English",
    "total_pages": 14,
    "gdrive_url": "https://drive.google.com/drive/folders/1KdbLY8DMET-kb4LrN1I1POnzy0svcmwB"
  },
  {
    "subject": "Santoor (English)",
    "chapter": 9,
    "title": "Vocation",
    "file": "eesa109.pdf",
    "folder": "English",
    "total_pages": 14,
    "gdrive_url": "https://drive.google.com/drive/folders/1KdbLY8DMET-kb4LrN1I1POnzy0svcmwB"
  },
  {
    "subject": "Santoor (English)",
    "chapter": 10,
    "title": "Glass Bangles",
    "file": "eesa110.pdf",
    "folder": "English",
    "total_pages": 22,
    "gdrive_url": "https://drive.google.com/drive/folders/1KdbLY8DMET-kb4LrN1I1POnzy0svcmwB"
  },
  {
    "subject": "English Grammar",
    "chapter": 1,
    "title": "Chapter 1",
    "file": "High School English Grammar and Composition Book.pdf",
    "folder": "EnglishGrammer",
    "total_pages": 421,
    "gdrive_url": "https://drive.google.com/drive/folders/1KdbLY8DMET-kb4LrN1I1POnzy0svcmwB"
  },
  {
    "subject": "Maths Mela (Mathematics)",
    "chapter": 1,
    "title": "We the Travellers — I",
    "file": "eemm101.pdf",
    "folder": "Math",
    "total_pages": 16,
    "gdrive_url": "https://drive.google.com/drive/folders/1KdbLY8DMET-kb4LrN1I1POnzy0svcmwB"
  },
  {
    "subject": "Maths Mela (Mathematics)",
    "chapter": 2,
    "title": "Fractions",
    "file": "eemm102.pdf",
    "folder": "Math",
    "total_pages": 15,
    "gdrive_url": "https://drive.google.com/drive/folders/1KdbLY8DMET-kb4LrN1I1POnzy0svcmwB"
  },
  {
    "subject": "Maths Mela (Mathematics)",
    "chapter": 3,
    "title": "Angles as Turns",
    "file": "eemm103.pdf",
    "folder": "Math",
    "total_pages": 10,
    "gdrive_url": "https://drive.google.com/drive/folders/1KdbLY8DMET-kb4LrN1I1POnzy0svcmwB"
  },
  {
    "subject": "Maths Mela (Mathematics)",
    "chapter": 4,
    "title": "We the Travellers — II",
    "file": "eemm104.pdf",
    "folder": "Math",
    "total_pages": 15,
    "gdrive_url": "https://drive.google.com/drive/folders/1KdbLY8DMET-kb4LrN1I1POnzy0svcmwB"
  },
  {
    "subject": "Maths Mela (Mathematics)",
    "chapter": 5,
    "title": "Far and Near",
    "file": "eemm105.pdf",
    "folder": "Math",
    "total_pages": 13,
    "gdrive_url": "https://drive.google.com/drive/folders/1KdbLY8DMET-kb4LrN1I1POnzy0svcmwB"
  },
  {
    "subject": "Maths Mela (Mathematics)",
    "chapter": 6,
    "title": "The Dairy Farm",
    "file": "eemm106.pdf",
    "folder": "Math",
    "total_pages": 22,
    "gdrive_url": "https://drive.google.com/drive/folders/1KdbLY8DMET-kb4LrN1I1POnzy0svcmwB"
  },
  {
    "subject": "Maths Mela (Mathematics)",
    "chapter": 7,
    "title": "Shapes and Patterns",
    "file": "eemm107.pdf",
    "folder": "Math",
    "total_pages": 12,
    "gdrive_url": "https://drive.google.com/drive/folders/1KdbLY8DMET-kb4LrN1I1POnzy0svcmwB"
  },
  {
    "subject": "Maths Mela (Mathematics)",
    "chapter": 8,
    "title": "Weight and Capacity",
    "file": "eemm108.pdf",
    "folder": "Math",
    "total_pages": 15,
    "gdrive_url": "https://drive.google.com/drive/folders/1KdbLY8DMET-kb4LrN1I1POnzy0svcmwB"
  },
  {
    "subject": "Maths Mela (Mathematics)",
    "chapter": 9,
    "title": "Coconut Farm",
    "file": "eemm109.pdf",
    "folder": "Math",
    "total_pages": 17,
    "gdrive_url": "https://drive.google.com/drive/folders/1KdbLY8DMET-kb4LrN1I1POnzy0svcmwB"
  },
  {
    "subject": "Maths Mela (Mathematics)",
    "chapter": 10,
    "title": "Symmetrical Designs",
    "file": "eemm110.pdf",
    "folder": "Math",
    "total_pages": 6,
    "gdrive_url": "https://drive.google.com/drive/folders/1KdbLY8DMET-kb4LrN1I1POnzy0svcmwB"
  },
  {
    "subject": "Maths Mela (Mathematics)",
    "chapter": 11,
    "title": "Grandmother's Quilt",
    "file": "eemm111.pdf",
    "folder": "Math",
    "total_pages": 13,
    "gdrive_url": "https://drive.google.com/drive/folders/1KdbLY8DMET-kb4LrN1I1POnzy0svcmwB"
  },
  {
    "subject": "Maths Mela (Mathematics)",
    "chapter": 12,
    "title": "Racing Seconds",
    "file": "eemm112.pdf",
    "folder": "Math",
    "total_pages": 9,
    "gdrive_url": "https://drive.google.com/drive/folders/1KdbLY8DMET-kb4LrN1I1POnzy0svcmwB"
  },
  {
    "subject": "Maths Mela (Mathematics)",
    "chapter": 13,
    "title": "Animal Jumps",
    "file": "eemm113.pdf",
    "folder": "Math",
    "total_pages": 7,
    "gdrive_url": "https://drive.google.com/drive/folders/1KdbLY8DMET-kb4LrN1I1POnzy0svcmwB"
  },
  {
    "subject": "Maths Mela (Mathematics)",
    "chapter": 14,
    "title": "Maps and Locations",
    "file": "eemm114.pdf",
    "folder": "Math",
    "total_pages": 8,
    "gdrive_url": "https://drive.google.com/drive/folders/1KdbLY8DMET-kb4LrN1I1POnzy0svcmwB"
  },
  {
    "subject": "Maths Mela (Mathematics)",
    "chapter": 15,
    "title": "Data Through Pictures",
    "file": "eemm115.pdf",
    "folder": "Math",
    "total_pages": 22,
    "gdrive_url": "https://drive.google.com/drive/folders/1KdbLY8DMET-kb4LrN1I1POnzy0svcmwB"
  },
  {
    "subject": "Our Wondrous World (Science & EVS)",
    "chapter": 1,
    "title": "Water — The Essence of Life",
    "file": "eeev101.pdf",
    "folder": "OurWondrousWorld",
    "total_pages": 20,
    "gdrive_url": "https://drive.google.com/drive/folders/1KdbLY8DMET-kb4LrN1I1POnzy0svcmwB"
  },
  {
    "subject": "Our Wondrous World (Science & EVS)",
    "chapter": 2,
    "title": "Journey of a River",
    "file": "eeev102.pdf",
    "folder": "OurWondrousWorld",
    "total_pages": 17,
    "gdrive_url": "https://drive.google.com/drive/folders/1KdbLY8DMET-kb4LrN1I1POnzy0svcmwB"
  },
  {
    "subject": "Our Wondrous World (Science & EVS)",
    "chapter": 3,
    "title": "The Mystery of Food",
    "file": "eeev103.pdf",
    "folder": "OurWondrousWorld",
    "total_pages": 17,
    "gdrive_url": "https://drive.google.com/drive/folders/1KdbLY8DMET-kb4LrN1I1POnzy0svcmwB"
  },
  {
    "subject": "Our Wondrous World (Science & EVS)",
    "chapter": 4,
    "title": "Our School — A Happy Place",
    "file": "eeev104.pdf",
    "folder": "OurWondrousWorld",
    "total_pages": 18,
    "gdrive_url": "https://drive.google.com/drive/folders/1KdbLY8DMET-kb4LrN1I1POnzy0svcmwB"
  },
  {
    "subject": "Our Wondrous World (Science & EVS)",
    "chapter": 5,
    "title": "Our Vibrant Country",
    "file": "eeev105.pdf",
    "folder": "OurWondrousWorld",
    "total_pages": 21,
    "gdrive_url": "https://drive.google.com/drive/folders/1KdbLY8DMET-kb4LrN1I1POnzy0svcmwB"
  },
  {
    "subject": "Our Wondrous World (Science & EVS)",
    "chapter": 6,
    "title": "Some Unique Places",
    "file": "eeev106.pdf",
    "folder": "OurWondrousWorld",
    "total_pages": 18,
    "gdrive_url": "https://drive.google.com/drive/folders/1KdbLY8DMET-kb4LrN1I1POnzy0svcmwB"
  },
  {
    "subject": "Our Wondrous World (Science & EVS)",
    "chapter": 7,
    "title": "Energy — How Things Work",
    "file": "eeev107.pdf",
    "folder": "OurWondrousWorld",
    "total_pages": 19,
    "gdrive_url": "https://drive.google.com/drive/folders/1KdbLY8DMET-kb4LrN1I1POnzy0svcmwB"
  },
  {
    "subject": "Our Wondrous World (Science & EVS)",
    "chapter": 8,
    "title": "Clothes — How Things are Made",
    "file": "eeev108.pdf",
    "folder": "OurWondrousWorld",
    "total_pages": 14,
    "gdrive_url": "https://drive.google.com/drive/folders/1KdbLY8DMET-kb4LrN1I1POnzy0svcmwB"
  },
  {
    "subject": "Our Wondrous World (Science & EVS)",
    "chapter": 9,
    "title": "Rhythms of Nature",
    "file": "eeev109.pdf",
    "folder": "OurWondrousWorld",
    "total_pages": 16,
    "gdrive_url": "https://drive.google.com/drive/folders/1KdbLY8DMET-kb4LrN1I1POnzy0svcmwB"
  },
  {
    "subject": "Our Wondrous World (Science & EVS)",
    "chapter": 10,
    "title": "Earth — Our Shared Home",
    "file": "eeev110.pdf",
    "folder": "OurWondrousWorld",
    "total_pages": 24,
    "gdrive_url": "https://drive.google.com/drive/folders/1KdbLY8DMET-kb4LrN1I1POnzy0svcmwB"
  }
];

  // In-memory full textbook pages loaded dynamically from textbooks_db.json
  let textbookPages = [];
  let isLoaded = false;

  const STOP_WORDS = new Set([
    "what", "is", "the", "in", "a", "an", "and", "or", "of", "to", "for",
    "from", "why", "how", "do", "does", "did", "where", "who", "which",
    "are", "tell", "explain", "about", "rishit", "can", "you", "me", "please",
    "give", "with", "that", "this", "these", "those", "check", "show", "read", "look"
  ]);

  function init() {
    return fetch('data/textbooks_db.json')
      .then(res => {
        if (!res.ok) throw new Error("HTTP " + res.status);
        return res.json();
      })
      .then(pages => {
        textbookPages = pages;
        isLoaded = true;
        console.log(`ClassTutor: Loaded ${textbookPages.length} textbook pages dynamically.`);
        return textbookPages;
      })
      .catch(err => {
        console.warn("ClassTutor: Loading textbooks_db.json fallback to syllabus index", err);
        return [];
      });
  }

  // Auto-init immediately
  init();

  function tokenize(text) {
    return (text || '').toLowerCase()
      .replace(/[^\w\s]/g, ' ')
      .split(/\s+/)
      .filter(w => w.length > 2 && !STOP_WORDS.has(w));
  }

  function getSubjects() {
    const subs = new Set();
    SYLLABUS.forEach(s => subs.add(s.subject));
    return Array.from(subs);
  }

  function search(query) {
    const q = (query || '').trim().toLowerCase();
    const tokens = tokenize(q);

    // 1. Handle Greetings (warm welcome for Rishit)
    if (/^(hi|hello|hey|good\s*(morning|afternoon|evening)|namaste)\b/i.test(q) && tokens.length <= 2) {
      const res = [{
        isSpecial: true,
        specialType: "greeting",
        subject: "ClassTutor",
        chapter: "Welcome",
        summary: "Hello Rishit! I am your ClassTutor. You can ask me anything from your Standard 5 textbooks in Science (Our Wondrous World), Mathematics (Maths Mela), English (Santoor), and your worksheets!",
        file: "",
        page: 1
      }];
      res.surfingMeta = {
        pagesScanned: 0,
        durationMs: 0,
        matchedSubject: "ClassTutor",
        matchedChapter: "Welcome",
        matchedPage: 1,
        matchedTopic: "Greetings & Instructions",
        score: 100,
        totalMatches: 1
      };
      return res;
    }

    // 2. Handle Subject / Curriculum inquiries
    if (/(subject|syllabus|chapters|books|what\s+do\s+we\s+study|list\s+subjects)/i.test(q)) {
      const subs = getSubjects();
      const res = [{
        isSpecial: true,
        specialType: "syllabus",
        subject: "CBSE Standard 5 Curriculum",
        chapter: "Subjects Overview",
        summary: `Your Standard 5 subjects are: ${subs.join(', ')}. All chapters are loaded directly from your official textbooks.`,
        file: "",
        page: 1
      }];
      res.surfingMeta = {
        pagesScanned: 0,
        durationMs: 0,
        matchedSubject: "CBSE Standard 5",
        matchedChapter: "Syllabus Overview",
        matchedPage: 1,
        matchedTopic: subs.join(", "),
        score: 100,
        totalMatches: 1
      };
      return res;
    }

    if (tokens.length === 0) return [];

    // 3. Dynamic Search over all loaded pages
    const startTime = (typeof performance !== 'undefined') ? performance.now() : Date.now();
    const pagesToSearch = textbookPages.length > 0 ? textbookPages : [];
    const scored = [];

    if (pagesToSearch.length > 0) {
      for (const p of pagesToSearch) {
        const textLower = (p.text || '').toLowerCase();
        const titleLower = ((p.chapter_title || '') + ' ' + (p.subject || '')).toLowerCase();

        let score = 0;
        let matchedTokens = 0;

        for (const tok of tokens) {
          const tokStem = tok.replace(/ll/g, 'l');
          const hitTitle = titleLower.includes(tok) || (tokStem.length > 4 && titleLower.replace(/ll/g, 'l').includes(tokStem));
          const hitText = textLower.includes(tok) || (tokStem.length > 4 && textLower.replace(/ll/g, 'l').includes(tokStem));
          if (hitTitle) {
            score += 15;
            matchedTokens++;
          }
          if (hitText) {
            score += 5;
            matchedTokens++;
          }
        }

        if (matchedTokens >= 2) {
          score *= (1 + matchedTokens * 0.5);
        }

        if (score > 12) {
          scored.push({
            score,
            subject: p.subject,
            chapter: p.chapter_title,
            file: p.file,
            folder: p.folder,
            page: p.page,
            summary: `Subject: ${p.subject} | Chapter: ${p.chapter_title} (Page ${p.page})\n${p.text.slice(0, 600)}`
          });
        }
      }
    } else {
      // Fallback if textbooks_db.json is still fetching over network
      for (const s of SYLLABUS) {
        const textLower = ((s.title || '') + ' ' + (s.subject || '')).toLowerCase();
        let score = 0;
        let matchedTokens = 0;
        for (const tok of tokens) {
          if (textLower.includes(tok)) {
            score += 20;
            matchedTokens++;
          }
        }
        if (score > 15) {
          scored.push({
            score,
            subject: s.subject,
            chapter: s.title,
            file: s.file,
            folder: s.folder,
            page: 1,
            summary: `Subject: ${s.subject} | Chapter: ${s.title} (${s.file})`
          });
        }
      }
    }

    scored.sort((a, b) => b.score - a.score);
    const duration = Math.round(((typeof performance !== 'undefined') ? performance.now() : Date.now()) - startTime);
    const top = scored[0] || null;

    // Check if query is asking for chapter-level overview, topics, or questions
    const isChapterQuery = /(topic|topics|question|questions|summary|overview|all|exercise|exercises|puzzles)/i.test(q);
    let finalResults = [];

    if (top && isChapterQuery && top.file && pagesToSearch.length > 0) {
      // Retrieve full breadth of the matched chapter (up to 12 pages)
      const isQuestionSpecific = /(question|questions|exercise|exercises|problem|problems|puzzle|puzzles|fill in)/i.test(q);
      const chapterPages = pagesToSearch.filter(p => p.file === top.file);

      let selectedPages = [];
      if (isQuestionSpecific) {
        const qPages = chapterPages.filter(p => /(question|fill in|find|calculate|how many|puzzle|discuss|solve|let us|write|count)/i.test(p.text || ''));
        selectedPages = qPages.length >= 3 ? qPages.slice(0, 12) : chapterPages.slice(0, 12);
      } else {
        selectedPages = chapterPages.slice(0, 12);
      }

      finalResults = selectedPages.map(p => ({
        score: top.score,
        subject: p.subject,
        chapter: p.chapter_title,
        file: p.file,
        folder: p.folder,
        page: p.page,
        summary: `Subject: ${p.subject} | Chapter: ${p.chapter_title} (Page ${p.page})\n${(p.text || '').slice(0, 500)}`
      }));
      finalResults.isChapterOverview = true;
    } else {
      finalResults = scored.slice(0, 3);
    }

    finalResults.surfingMeta = {
      pagesScanned: pagesToSearch.length || SYLLABUS.length,
      durationMs: duration,
      matchedSubject: top ? top.subject : "None",
      matchedChapter: top ? top.chapter : "Not Found",
      matchedPage: top ? top.page : 0,
      matchedTopic: tokens.slice(0, 4).join(", "),
      score: top ? Math.round(top.score) : 0,
      totalMatches: scored.length
    };

    return finalResults;
  }

  return {
    init,
    search,
    getSubjects,
    get isLoaded() { return isLoaded; },
    GDRIVE_FOLDER_URL
  };
})();
